// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0kO5MDsAJTWdDwFN80O6Qth44a2yYqD8',
    appId: '1:66315162842:web:9fb93a68ab69e03bc2c1e3',
    messagingSenderId: '66315162842',
    projectId: 'hallify-df669',
    authDomain: 'hallify-df669.firebaseapp.com',
    storageBucket: 'hallify-df669.firebasestorage.app',
    measurementId: 'G-ZSSTKEMTRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB60AuVVaU0Y2PEj1EVbWSo2fkFhqrXaSA',
    appId: '1:66315162842:android:fe506ebb8b8d17d3c2c1e3',
    messagingSenderId: '66315162842',
    projectId: 'hallify-df669',
    storageBucket: 'hallify-df669.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMQhG7X6SxDtqO5RnS1KEqfNlZRQhN3gQ',
    appId: '1:66315162842:ios:f445fb418e94f36dc2c1e3',
    messagingSenderId: '66315162842',
    projectId: 'hallify-df669',
    storageBucket: 'hallify-df669.firebasestorage.app',
    iosBundleId: 'com.example.hallify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMQhG7X6SxDtqO5RnS1KEqfNlZRQhN3gQ',
    appId: '1:66315162842:ios:f445fb418e94f36dc2c1e3',
    messagingSenderId: '66315162842',
    projectId: 'hallify-df669',
    storageBucket: 'hallify-df669.firebasestorage.app',
    iosBundleId: 'com.example.hallify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0kO5MDsAJTWdDwFN80O6Qth44a2yYqD8',
    appId: '1:66315162842:web:464fe3695875ef18c2c1e3',
    messagingSenderId: '66315162842',
    projectId: 'hallify-df669',
    authDomain: 'hallify-df669.firebaseapp.com',
    storageBucket: 'hallify-df669.firebasestorage.app',
    measurementId: 'G-YG618QJVLZ',
  );
}
