// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_WEB_API_KEY', defaultValue: 'AIzaSyB0kO5MDsAJTWdDwFN80O6Qth44a2yYqD8'),
    appId: String.fromEnvironment('FIREBASE_WEB_APP_ID', defaultValue: '1:66315162842:web:9fb93a68ab69e03bc2c1e3'),
    messagingSenderId: String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID', defaultValue: '66315162842'),
    projectId: String.fromEnvironment('FIREBASE_PROJECT_ID', defaultValue: 'hallify-df669'),
    authDomain: String.fromEnvironment('FIREBASE_AUTH_DOMAIN', defaultValue: 'hallify-df669.firebaseapp.com'),
    storageBucket: String.fromEnvironment('FIREBASE_STORAGE_BUCKET', defaultValue: 'hallify-df669.firebasestorage.app'),
    measurementId: String.fromEnvironment('FIREBASE_WEB_MEASUREMENT_ID', defaultValue: 'G-ZSSTKEMTRL'),
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_ANDROID_API_KEY', defaultValue: 'AIzaSyB60AuVVaU0Y2PEj1EVbWSo2fkFhqrXaSA'),
    appId:
        String.fromEnvironment('FIREBASE_ANDROID_APP_ID', defaultValue: '1:66315162842:android:fe506ebb8b8d17d3c2c1e3'),
    messagingSenderId: String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID', defaultValue: '66315162842'),
    projectId: String.fromEnvironment('FIREBASE_PROJECT_ID', defaultValue: 'hallify-df669'),
    storageBucket: String.fromEnvironment('FIREBASE_STORAGE_BUCKET', defaultValue: 'hallify-df669.firebasestorage.app'),
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_IOS_API_KEY', defaultValue: 'AIzaSyCMQhG7X6SxDtqO5RnS1KEqfNlZRQhN3gQ'),
    appId: String.fromEnvironment('FIREBASE_IOS_APP_ID', defaultValue: '1:66315162842:ios:f445fb418e94f36dc2c1e3'),
    messagingSenderId: String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID', defaultValue: '66315162842'),
    projectId: String.fromEnvironment('FIREBASE_PROJECT_ID', defaultValue: 'hallify-df669'),
    storageBucket: String.fromEnvironment('FIREBASE_STORAGE_BUCKET', defaultValue: 'hallify-df669.firebasestorage.app'),
    iosBundleId: String.fromEnvironment('FIREBASE_IOS_BUNDLE_ID', defaultValue: 'com.example.hallify'),
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_IOS_API_KEY', defaultValue: 'AIzaSyCMQhG7X6SxDtqO5RnS1KEqfNlZRQhN3gQ'),
    appId: String.fromEnvironment('FIREBASE_IOS_APP_ID', defaultValue: '1:66315162842:ios:f445fb418e94f36dc2c1e3'),
    messagingSenderId: String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID', defaultValue: '66315162842'),
    projectId: String.fromEnvironment('FIREBASE_PROJECT_ID', defaultValue: 'hallify-df669'),
    storageBucket: String.fromEnvironment('FIREBASE_STORAGE_BUCKET', defaultValue: 'hallify-df669.firebasestorage.app'),
    iosBundleId: String.fromEnvironment('FIREBASE_IOS_BUNDLE_ID', defaultValue: 'com.example.hallify'),
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_WINDOWS_API_KEY', defaultValue: 'AIzaSyB0kO5MDsAJTWdDwFN80O6Qth44a2yYqD8'),
    appId: String.fromEnvironment('FIREBASE_WINDOWS_APP_ID', defaultValue: '1:66315162842:web:464fe3695875ef18c2c1e3'),
    messagingSenderId: String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID', defaultValue: '66315162842'),
    projectId: String.fromEnvironment('FIREBASE_PROJECT_ID', defaultValue: 'hallify-df669'),
    authDomain: String.fromEnvironment('FIREBASE_AUTH_DOMAIN', defaultValue: 'hallify-df669.firebaseapp.com'),
    storageBucket: String.fromEnvironment('FIREBASE_STORAGE_BUCKET', defaultValue: 'hallify-df669.firebasestorage.app'),
    measurementId: String.fromEnvironment('FIREBASE_WINDOWS_MEASUREMENT_ID', defaultValue: 'G-YG618QJVLZ'),
  );
}
